import requests
import json
import os
from datetime import datetime

# Your Graph API endpoint
url = "https://graph.microsoft.com/v1.0/me/messages?$top=30&$select=subject,bodyPreview,from,toRecipients"

# Put your token here (keep it private!)
token = "eyJ0eXAiOiJKV1QiLCJub25jZSI6Ii1mS0t5bmwxRmYxNi1MZ3lXS0RqWHJHUHB0cTJ4b18xdDFXMlM0SHRlZEUiLCJhbGciOiJSUzI1NiIsIng1dCI6IkpZaEFjVFBNWl9MWDZEQmxPV1E3SG4wTmVYRSIsImtpZCI6IkpZaEFjVFBNWl9MWDZEQmxPV1E3SG4wTmVYRSJ9.eyJhdWQiOiIwMDAwMDAwMy0wMDAwLTAwMDAtYzAwMC0wMDAwMDAwMDAwMDAiLCJpc3MiOiJodHRwczovL3N0cy53aW5kb3dzLm5ldC8zNDUzMTMxOC03MDExLTRmZDQtODdmMC1hNDM4MTZjNDliZDAvIiwiaWF0IjoxNzU1NTIwNjI2LCJuYmYiOjE3NTU1MjA2MjYsImV4cCI6MTc1NTYwNzMyNiwiYWNjdCI6MCwiYWNyIjoiMSIsImFpbyI6IkFWUUFxLzhaQUFBQUNOK1JGWk1pZWRuRnhGY1oweGh1bzg4eVkyb212b2NxOFNrYnltdnJUQzFLdklzcVV6ZjFrR2x0VE1sZnBMWURlZHZsRW9mbE1PdGJ5dmRkRnQvUnd4QktOVXJOcnI3aDJmcmxwcVRmeUZZPSIsImFtciI6WyJwd2QiXSwiYXBwX2Rpc3BsYXluYW1lIjoiR3JhcGggRXhwbG9yZXIiLCJhcHBpZCI6ImRlOGJjOGI1LWQ5ZjktNDhiMS1hOGFkLWI3NDhkYTcyNTA2NCIsImFwcGlkYWNyIjoiMCIsImZhbWlseV9uYW1lIjoiTW9oaXVkZGluIiwiZ2l2ZW5fbmFtZSI6Ik11c3RhZmEiLCJpZHR5cCI6InVzZXIiLCJpcGFkZHIiOiIxMzAuNjMuMTY1LjEyMiIsIm5hbWUiOiJNdXN0YWZhIE1vaGl1ZGRpbiIsIm9pZCI6IjU0Zjk3Njc0LTFmN2YtNDY1MS05MzM3LTEwNmVkMTFjYmUyYiIsIm9ucHJlbV9zaWQiOiJTLTEtNS0yMS0yNDUyNTgyNTI0LTM2OTU0MDkzMi0xNjIwNjgxMDI3LTg5MTk4OSIsInBsYXRmIjoiMyIsInB1aWQiOiIxMDAzMjAwNDk5NTA0RTU4IiwicmgiOiIxLkFSc0FHQk5UTkJGdzFFLUg4S1E0RnNTYjBBTUFBQUFBQUFBQXdBQUFBQUFBQUFCc0FYY2JBQS4iLCJzY3AiOiJDYWxlbmRhcnMuUmVhZFdyaXRlIENoYW5uZWwuUmVhZEJhc2ljLkFsbCBDaGFubmVsTWVzc2FnZS5SZWFkLkFsbCBDaGFubmVsU2V0dGluZ3MuUmVhZC5BbGwgQ2hhbm5lbFNldHRpbmdzLlJlYWRXcml0ZS5BbGwgQ29udGFjdHMuUmVhZFdyaXRlIERpcmVjdG9yeS5SZWFkLkFsbCBEaXJlY3RvcnkuUmVhZFdyaXRlLkFsbCBGaWxlcy5SZWFkV3JpdGUuQWxsIEdyb3VwLlJlYWQuQWxsIElkZW50aXR5Umlza3lVc2VyLlJlYWQuQWxsIE1haWwuUmVhZC5TaGFyZWQgTWFpbC5SZWFkV3JpdGUgTm90ZXMuUmVhZFdyaXRlLkFsbCBvcGVuaWQgUGVvcGxlLlJlYWQgcHJvZmlsZSBTaXRlcy5SZWFkV3JpdGUuQWxsIFRhc2tzLlJlYWRXcml0ZSBVc2VyLlJlYWQgVXNlci5SZWFkLkFsbCBVc2VyLlJlYWRCYXNpYy5BbGwgVXNlci5SZWFkV3JpdGUgVXNlci5SZWFkV3JpdGUuQWxsIGVtYWlsIiwic2lkIjoiMDA1MDk4ZTktYWE5NC1jZjlmLWI4MmQtMGU3ZGE2MjNiZWYyIiwic2lnbmluX3N0YXRlIjpbImttc2kiXSwic3ViIjoibC1hVHFvNDBReUh3VzVvUFc5ZVFwVWhXeWhubkUtM0taRlB0S0ZOQ1JRYyIsInRlbmFudF9yZWdpb25fc2NvcGUiOiJOQSIsInRpZCI6IjM0NTMxMzE4LTcwMTEtNGZkNC04N2YwLWE0MzgxNmM0OWJkMCIsInVuaXF1ZV9uYW1lIjoibXVzMTBmYWFAeW9ya3UuY2EiLCJ1cG4iOiJtdXMxMGZhYUB5b3JrdS5jYSIsInV0aSI6IlJodTctQXpxY2s2WUVBTm96TzRFQUEiLCJ2ZXIiOiIxLjAiLCJ3aWRzIjpbImI3OWZiZjRkLTNlZjktNDY4OS04MTQzLTc2YjE5NGU4NTUwOSJdLCJ4bXNfY2MiOlsiQ1AxIl0sInhtc19mdGQiOiJScnBCc3RRLVVTTmFELXFmbjdtcGVUelRmVXEzUUIwZzN2WkhEMWxkaVk4QmRYTnViM0owYUMxa2MyMXoiLCJ4bXNfaWRyZWwiOiIxIDI4IiwieG1zX3NzbSI6IjEiLCJ4bXNfc3QiOnsic3ViIjoidFg0TmtqbnVMdXZ3MG9qSlhGTTJuOGJNMWpsZVF0VHF1ZWpMLVQ2YU5LcyJ9LCJ4bXNfdGNkdCI6MTQ5MDM4NDEyNX0.VFBLFIBEk8eYo9RNeyiRAJxsZt4vy0K9IfXoofh5W8npnP4bzU7FFZka8RhLoPSjJGcX5W1yxMDZzyt-YtwPa63OiA3WU5JSg8q-3BNiaYV-ed-BOqj93Gp1kMci5gAgf0um6taeIwYBUtttPzpjCCVkmaqQPleCVB3RMqDLKhIojKrgAmSMEoBawsEHKWrZ_44iVdlJ4rtGd-JkK2qChVCPDDYYXVoh8giwXZXufv8wTwifU6vE0bnrPj3B6gBhkt3q4U9ev6dz5Q-9YMDLEm2vl4-Kg9TPS_JFKpzGWliaTw54t_sovmWfwTPcTTCpximh6jcZnLSZtzYI_DyY7w"

headers = {
    "Authorization": f"Bearer {token}",
    "Content-Type": "application/json"
}

response = requests.get(url, headers=headers)

if response.status_code == 200:
    data = response.json()
    
    # Get today's date for filename
    today = datetime.now().strftime("%Y-%m-%d")
    
    # Path to Desktop with date in filename
    desktop_path = os.path.join(os.path.expanduser("~"), "Desktop", f"emails_{today}.json")
    
    # Save JSON on Desktop
    with open(desktop_path, "w", encoding="utf-8") as f:
        json.dump(data, f, indent=4, ensure_ascii=False)
    
    print(f"✅ Emails downloaded successfully! Saved to {desktop_path}")
else:
    print("❌ Error:", response.status_code, response.text)
