import requests
import json
import os
from datetime import datetime

# Your Graph API endpoint
url = "https://graph.microsoft.com/v1.0/me/messages?$top=30&$select=subject,bodyPreview,from,toRecipients"

# Put your token here (keep it private!)
token = "eyJ0eXAiOiJKV1QiLCJub25jZSI6ImIwb1NaYjQ2V3hPcDdOQWZKWm5DRHJxam9lZVhQaHE2MXMyZnNpaWlUcTQiLCJhbGciOiJSUzI1NiIsIng1dCI6IkpZaEFjVFBNWl9MWDZEQmxPV1E3SG4wTmVYRSIsImtpZCI6IkpZaEFjVFBNWl9MWDZEQmxPV1E3SG4wTmVYRSJ9.eyJhdWQiOiIwMDAwMDAwMy0wMDAwLTAwMDAtYzAwMC0wMDAwMDAwMDAwMDAiLCJpc3MiOiJodHRwczovL3N0cy53aW5kb3dzLm5ldC8zNDUzMTMxOC03MDExLTRmZDQtODdmMC1hNDM4MTZjNDliZDAvIiwiaWF0IjoxNzU1NjA4MjUxLCJuYmYiOjE3NTU2MDgyNTEsImV4cCI6MTc1NTY5NDk1MSwiYWNjdCI6MCwiYWNyIjoiMSIsImFpbyI6IkFWUUFxLzhaQUFBQXB6akpNSG1SU3VwamdhRFRkazgwQUVDQlFqemFIRkR5TldNaTVVdmhqU2JDbm50d0YwT2FsdzhSTjRCRXl3MTA4TVpMeHZ2TGV6VTJqd0pRQUE5OXl2WFA2Y2UvK09RZmpjdWgrQmdGbzBvPSIsImFtciI6WyJwd2QiXSwiYXBwX2Rpc3BsYXluYW1lIjoiR3JhcGggRXhwbG9yZXIiLCJhcHBpZCI6ImRlOGJjOGI1LWQ5ZjktNDhiMS1hOGFkLWI3NDhkYTcyNTA2NCIsImFwcGlkYWNyIjoiMCIsImZhbWlseV9uYW1lIjoiTW9oaXVkZGluIiwiZ2l2ZW5fbmFtZSI6Ik11c3RhZmEiLCJpZHR5cCI6InVzZXIiLCJpcGFkZHIiOiIxMzAuNjMuMTY1LjEyMiIsIm5hbWUiOiJNdXN0YWZhIE1vaGl1ZGRpbiIsIm9pZCI6IjU0Zjk3Njc0LTFmN2YtNDY1MS05MzM3LTEwNmVkMTFjYmUyYiIsIm9ucHJlbV9zaWQiOiJTLTEtNS0yMS0yNDUyNTgyNTI0LTM2OTU0MDkzMi0xNjIwNjgxMDI3LTg5MTk4OSIsInBsYXRmIjoiMyIsInB1aWQiOiIxMDAzMjAwNDk5NTA0RTU4IiwicmgiOiIxLkFSc0FHQk5UTkJGdzFFLUg4S1E0RnNTYjBBTUFBQUFBQUFBQXdBQUFBQUFBQUFCc0FYY2JBQS4iLCJzY3AiOiJDYWxlbmRhcnMuUmVhZFdyaXRlIENoYW5uZWwuUmVhZEJhc2ljLkFsbCBDaGFubmVsTWVzc2FnZS5SZWFkLkFsbCBDaGFubmVsU2V0dGluZ3MuUmVhZC5BbGwgQ2hhbm5lbFNldHRpbmdzLlJlYWRXcml0ZS5BbGwgQ29udGFjdHMuUmVhZFdyaXRlIERpcmVjdG9yeS5SZWFkLkFsbCBEaXJlY3RvcnkuUmVhZFdyaXRlLkFsbCBGaWxlcy5SZWFkV3JpdGUuQWxsIEdyb3VwLlJlYWQuQWxsIElkZW50aXR5Umlza3lVc2VyLlJlYWQuQWxsIE1haWwuUmVhZC5TaGFyZWQgTWFpbC5SZWFkV3JpdGUgTm90ZXMuUmVhZFdyaXRlLkFsbCBvcGVuaWQgUGVvcGxlLlJlYWQgcHJvZmlsZSBTaXRlcy5SZWFkV3JpdGUuQWxsIFRhc2tzLlJlYWRXcml0ZSBVc2VyLlJlYWQgVXNlci5SZWFkLkFsbCBVc2VyLlJlYWRCYXNpYy5BbGwgVXNlci5SZWFkV3JpdGUgVXNlci5SZWFkV3JpdGUuQWxsIGVtYWlsIiwic2lkIjoiMDA1MDk4ZTktYWE5NC1jZjlmLWI4MmQtMGU3ZGE2MjNiZWYyIiwic2lnbmluX3N0YXRlIjpbImttc2kiXSwic3ViIjoibC1hVHFvNDBReUh3VzVvUFc5ZVFwVWhXeWhubkUtM0taRlB0S0ZOQ1JRYyIsInRlbmFudF9yZWdpb25fc2NvcGUiOiJOQSIsInRpZCI6IjM0NTMxMzE4LTcwMTEtNGZkNC04N2YwLWE0MzgxNmM0OWJkMCIsInVuaXF1ZV9uYW1lIjoibXVzMTBmYWFAeW9ya3UuY2EiLCJ1cG4iOiJtdXMxMGZhYUB5b3JrdS5jYSIsInV0aSI6Imw4LUtScjh0TTBhTXRVdnp6ZGdmQUEiLCJ2ZXIiOiIxLjAiLCJ3aWRzIjpbImI3OWZiZjRkLTNlZjktNDY4OS04MTQzLTc2YjE5NGU4NTUwOSJdLCJ4bXNfY2MiOlsiQ1AxIl0sInhtc19mdGQiOiJtc3dmcTJEdUxJZENBWW5KdWlJUTllblh3MGFoaW81OXc2MW5Sblp2ZDMwQmRYTnpiM1YwYUMxa2MyMXoiLCJ4bXNfaWRyZWwiOiIyIDEiLCJ4bXNfc3NtIjoiMSIsInhtc19zdCI6eyJzdWIiOiJ0WDROa2pudUx1dncwb2pKWEZNMm44Yk0xamxlUXRUcXVlakwtVDZhTktzIn0sInhtc190Y2R0IjoxNDkwMzg0MTI1fQ.CdBMTycu4YH5XstEYlDpAIIKd-JsCUTkTjzAlWA1XwGVFKzXx3M4WAr4rpudRQ8G-CemPgxAWdDRUmoIN-nNtig8D3khftdKf7LF6OE96HbRwSGXGdjyUNtkGTruKOSqqd9Z6AWwyR7CBJffbY2a3_JruAaO8MbvJB4z8hAdxXkwhUE2HGs9H7J5g-PQKq3pxKMABkxP0asCJOhavx5PiGq3DcXUzCeJjyKlx-T3l3qdTBqHQkdZQ208rU2hK_NIPHZIsgAfRHDdE4KN4GMvTuudVmQeKESJNZfRhAlAoRq9LDh6IjcZVP_XSJ8DRvhxdpRG_ehAPhedinkpL-DUFw"

headers = {
    "Authorization": f"Bearer {token}",
    "Content-Type": "application/json"
}

response = requests.get(url, headers=headers)

if response.status_code == 200:
    data = response.json()
    
    # Get today's date for filename
    today = datetime.now().strftime("%Y-%m-%d")
    
    # Path to Desktop with date in filename
    desktop_path = os.path.join(os.path.expanduser("~"), "Desktop", f"emails_{today}.json")
    
    # Save JSON on Desktop
    with open(desktop_path, "w", encoding="utf-8") as f:
        json.dump(data, f, indent=4, ensure_ascii=False)
    
    print(f"✅ Emails downloaded successfully! Saved to {desktop_path}")
else:
    print("❌ Error:", response.status_code, response.text)
